name: Lint and test

on:
  pull_request:
  workflow_call:

concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Lint api
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout 5m

  test:
    needs: [lint]
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.x, 1.24.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test ./...